site_name: 东华高中毕业生大学指北
site_url: https://musemok.github.io/university-guide/
site_author: Muse Mok

repo_name: GitHub
repo_url: https://github.com/musemok/university-guide
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections  # 添加：显示分组
    - navigation.expand    # 添加：自动展开导航
    - search.suggest
  palette: 
    primary: indigo

plugins:
  - search

nav:
  - 首页: index.md
  - 北京:
      - 北京大学:
          - 学校概况: beijing/pku/pku.md
  - 上海:
      - 复旦大学:
          - 学校概况: shanghai/fdu/fdu.md
  - 广东:
      - 中山大学:
          - 学校概况: guangdong/sysu/sysu.md
  - 山东:
      - 山东大学:
          - 学校概况: shandong/sdu/sdu.md